import { readdir, stat, writeFile } from "node:fs/promises";
import { join } from "node:path";
import sharp from "sharp";

const ROOT = "public";
const WIDTHS = [800, 1280];
const QUALITY = 75;

async function walk(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(path)));
    else if (entry.name.endsWith(".webp") && !/-(?:800|1280)\.webp$/.test(entry.name)) out.push(path);
  }
  return out;
}

const files = await walk(ROOT);
const records = [];

for (const file of files) {
  const image = sharp(file);
  const meta = await image.metadata();
  const width = meta.width ?? 0;
  const height = meta.height ?? 0;
  if (width <= 800) continue;

  const publicPath = "/" + file.replaceAll("\\", "/").replace(/^public\//, "");
  const stem = file.replace(/\.webp$/, "");
  const publicStem = publicPath.replace(/\.webp$/, "");
  const parts = [];

  for (const w of WIDTHS) {
    if (width <= w) continue;
    const dest = `${stem}-${w}.webp`;
    await sharp(file)
      .resize({ width: w, withoutEnlargement: true })
      .webp({ quality: QUALITY, effort: 5 })
      .toFile(dest);
    const kb = Math.round((await stat(dest)).size / 1024);
    console.log(`${publicPath} -> ${w}w ${kb}KB`);
    parts.push(`${publicStem}-${w}.webp ${w}w`);
  }

  parts.push(`${publicPath} ${width}w`);
  records.push({
    src: publicPath,
    srcSet: parts.join(", "),
    width,
    height,
  });
}

records.sort((a, b) => a.src.localeCompare(b.src));

const body = records
  .map(
    (r) =>
      `  ${JSON.stringify(r.src)}: { srcSet: ${JSON.stringify(r.srcSet)}, width: ${r.width}, height: ${r.height} }`,
  )
  .join(",\n");

await writeFile(
  "src/data/imageSrcset.ts",
  `/* Generated by scripts/gen-srcset.mjs — do not edit by hand. */\nexport const IMAGE_SRCSET: Record<\n  string,\n  { srcSet: string; width: number; height: number }\n> = {\n${body},\n};\n`,
);

console.log(`\nwrote ${records.length} srcset entries`);
